Repository Inner-Heaven/libzetta-rs, pull requests merged in 2019-08, with the labels that each got.

#71 chore(zpool): Big update to docs and cleanup all public API.
  Cargo.toml
  README.md
  run_tests.sh
  src/lib.rs
  src/zpool/description.rs
  src/zpool/mod.rs
  src/zpool/open3.rs
  src/zpool/properties.rs
  src/zpool/topology.rs
  src/zpool/vdev.rs
  tests/test_zpool.rs
Labels: Area: zpool, Priority: Critical, Status: In Progress, Type: Improvement

#74 chore: rename project to libzetta
  Cargo.toml
  README.md
  contributing.md
  run_tests.sh
  src/zpool/description.rs
  src/zpool/mod.rs
  src/zpool/open3.rs
  src/zpool/properties.rs
  src/zpool/topology.rs
  src/zpool/vdev.rs
  tests/test_zpool.rs
Labels: Effort: Easy, Priority: Critical, Status: Done, Type: Improvement

#76 ci: Add Cirrus-CI
  .cirrus.yml
  README.md
Labels: Area: ci, Effort: Medium, Priority: High, Status: In Progress, Type: Improvement

#80 fix(parsers): Add '%' to symbols grammar.
  src/parsers/mod.rs
  src/parsers/stdout.pest
Labels: Area: zpool, Effort: Easy, Priority: High, Status: Done, Type: Bug

#87 feat(zfs): Check existence of dataset.
  Cargo.toml
  README.md
  src/lib.rs
  src/parsers/mod.rs
  src/zfs/description.rs
  src/zfs/lzc.rs
  src/zfs/mod.rs
  src/zpool/description.rs
  src/zpool/mod.rs
  src/zpool/open3.rs
  src/zpool/vdev.rs
  tests/test_zfs.rs
  tests/test_zpool.rs
Labels: Area: zfs, Effort: Medium, Status: Done, Type: Feature
